# Generated by Django 4.2.5 on 2023-10-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[('1', 'Admin'), ('2', 'Moderator')], default='2'),
        ),
    ]
