# Generated by Django 4.2.5 on 2023-10-11 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
