# Generated by Django 4.2.5 on 2023-10-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
