# Generated by Django 4.2.5 on 2023-10-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_event_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='age',
        ),
    ]
