# Generated by Django 4.2.5 on 2023-10-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event_images/dummy.jpg', upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(blank=True, default='event_images/dummy.jpg', null=True, upload_to='event_images/'),
        ),
    ]
