# Generated by Django 4.2.5 on 2023-10-30 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_remove_event_image_alter_eventimage_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='myapi.event'),
        ),
    ]
